### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by GatoPharaoh** [osaatcioglu/whatsapp-cli#1]
I successfully installed `whatsapp-cli` but can't get started.

Are the any necessary steps to configure it?

I am getting the following when running `whatsapp-cli`

`/usr/local/lib/node_modules/whatsapp-cli/src/index.js:21
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)`

**Comment by osaatcioglu** [comment]
Thanks for trying it out. What are the node and npm versions? I will try to reproduce it.

`node --version & npm --version`

**Comment by GatoPharaoh** [comment]
thanks for looking into it 
node version is `v6.11.5`
npm version is `3.10.10`

which versions are you using respectively recommending?

**Comment by osaatcioglu** [comment]
I checked with the Node v6 and I saw that it is not working. I am using Node v8. I suggest you to use that version. I will also add a requirement in the Readme. 

Let me know if upgrading the version solves the issue. Thanks.
